{
 "title": "Außenklima",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperatur AHT20 & BMP280",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"aht20\" or r._measurement == \"bmp280\")\r\n  |> filter(fn: (r) => r._field == \"t_c\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\n"
    }
   ]
  },
  {
   "title": "°C",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"aht20\" or r._measurement == \"bmp280\")\r\n  |> filter(fn: (r) => r._field == \"t_c\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> last()\r\n  |> group()              // <-- removes grouping so mean() acts on all\r\n  |> mean()\r\n  |> set(key: \"_titel\", value: \"°C\")"
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit (rel%) - AHT20",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"aht20\")\r\n  |> filter(fn: (r) => r._field == \"rh_pct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "rel.%",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"aht20\")\r\n  |> filter(fn: (r) => r._field == \"rh_pct\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> last()\r\n  |> group()              // <-- removes grouping so mean() acts on all\r\n  |> mean()\r\n"
    }
   ]
  },
  {
   "title": "Durchschnitt",
   "type": "stat",
   "description": "über gewählten Zeitrahmen",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"aht20\" or r._measurement == \"bmp280\")\r\n  |> filter(fn: (r) => r._field == \"t_c\")\r\n  |> group()              // <-- removes grouping so mean() acts on all\r\n  |> mean()\r\n"
    }
   ]
  },
  {
   "title": "Luftdruck (hPA)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"bmp280\")\r\n  |> filter(fn: (r) => r._field == \"p_hpa\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "eCO2 (ppm) - tvoc (ppb)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ens160\")\r\n  |> filter(fn: (r) => r._field == \"eco2_ppm\" or r._field == \"tvoc_ppb\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Air Quality Index",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ens160\")\r\n  |> filter(fn: (r) => r._field == \"aqi\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}