{
 "title": "Stromverbrauch",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "51D2 Power - Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"51D2\")\r\n  |> filter(fn: (r) => r._field == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {}
   ]
  },
  {
   "title": "Watt",
   "type": "stat",
   "description": "aktueller Verbrauch",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"51D2\")\r\n  |> filter(fn: (r) => r._field == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "51D2 Consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"51D2\")\r\n  |> filter(fn: (r) => r._field == \"Consumption\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {}
   ]
  },
  {
   "title": "Verbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data = from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"51D2\")\r\n  |> filter(fn: (r) => r._field == \"Consumption\")\r\n\r\nfirstVal = data |> first()\r\nlastVal  = data |> last()\r\n\r\nunion(tables: [firstVal, lastVal])\r\n  |> group()  // merge all rows into one table\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value\r\n      })\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _value: if r.last - r.first >= 0 then r.last - r.first else -(r.last - r.first),\r\n      _field: \"delta_Consumption\"\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "7821 Power - PC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"7821\")\r\n  |> filter(fn: (r) => r._field == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {}
   ]
  },
  {
   "title": "Watt",
   "type": "stat",
   "description": "aktueller Verbrauch",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"7821\")\r\n  |> filter(fn: (r) => r._field == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "7821 Consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"7821\")\r\n  |> filter(fn: (r) => r._field == \"Consumption\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {}
   ]
  },
  {
   "title": "Verbrauch",
   "type": "stat",
   "description": "im gewählten Zeitraum",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "data = from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"7821\")\r\n  |> filter(fn: (r) => r._field == \"Consumption\")\r\n\r\nfirstVal = data |> first()\r\nlastVal  = data |> last()\r\n\r\nunion(tables: [firstVal, lastVal])\r\n  |> group()  // merge all rows into one table\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value\r\n      })\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _value: if r.last - r.first >= 0 then r.last - r.first else -(r.last - r.first),\r\n      _field: \"delta_Consumption\"\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "531C Power - Waschmaschine & Geschirrspüler",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"531C\")\r\n  |> filter(fn: (r) => r._field == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {}
   ]
  },
  {
   "title": "Watt",
   "type": "stat",
   "description": "aktueller Verbrauch",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"531C\")\r\n  |> filter(fn: (r) => r._field == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "531C Consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"531C\")\r\n  |> filter(fn: (r) => r._field == \"Consumption\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {}
   ]
  },
  {
   "title": "Verbrauch",
   "type": "stat",
   "description": "im gewählten Zeitraum",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "data = from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"531C\")\r\n  |> filter(fn: (r) => r._field == \"Consumption\")\r\n\r\nfirstVal = data |> first()\r\nlastVal  = data |> last()\r\n\r\nunion(tables: [firstVal, lastVal])\r\n  |> group()  // merge all rows into one table\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value\r\n      })\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _value: if r.last - r.first >= 0 then r.last - r.first else -(r.last - r.first),\r\n      _field: \"delta_Consumption\"\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "7E65 Power - Monitor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"7E65\")\r\n  |> filter(fn: (r) => r._field == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {}
   ]
  },
  {
   "title": "Watt",
   "type": "stat",
   "description": "aktueller Verbrauch",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"7E65\")\r\n  |> filter(fn: (r) => r._field == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "7E65 Consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"7E65\")\r\n  |> filter(fn: (r) => r._field == \"Consumption\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {}
   ]
  },
  {
   "title": "Verbrauch",
   "type": "stat",
   "description": "im gewählten Zeitraum",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "data = from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"7E65\")\r\n  |> filter(fn: (r) => r._field == \"Consumption\")\r\n\r\nfirstVal = data |> first()\r\nlastVal  = data |> last()\r\n\r\nunion(tables: [firstVal, lastVal])\r\n  |> group()  // merge all rows into one table\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value\r\n      })\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _value: if r.last - r.first >= 0 then r.last - r.first else -(r.last - r.first),\r\n      _field: \"delta_Consumption\"\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "7E3A Power - Kühlschrank",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"7E3A\")\r\n  |> filter(fn: (r) => r._field == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {}
   ]
  },
  {
   "title": "Watt",
   "type": "stat",
   "description": "aktueller Verbrauch",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"7E3A\")\r\n  |> filter(fn: (r) => r._field == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "7E3A Consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"7E3A\")\r\n  |> filter(fn: (r) => r._field == \"Consumption\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {}
   ]
  },
  {
   "title": "Verbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data = from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"7E3A\")\r\n  |> filter(fn: (r) => r._field == \"Consumption\")\r\n\r\nfirstVal = data |> first()\r\nlastVal  = data |> last()\r\n\r\nunion(tables: [firstVal, lastVal])\r\n  |> group()  // merge all rows into one table\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value\r\n      })\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _value: if r.last - r.first >= 0 then r.last - r.first else -(r.last - r.first),\r\n      _field: \"delta_Consumption\"\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "770C Power - Heißluftfritteuse",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"770C\")\r\n  |> filter(fn: (r) => r._field == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {}
   ]
  },
  {
   "title": "Watt",
   "type": "stat",
   "description": "aktueller Verbrauch",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"770C\")\r\n  |> filter(fn: (r) => r._field == \"Power\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "770C Consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"770C\")\r\n  |> filter(fn: (r) => r._field == \"Consumption\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {}
   ]
  },
  {
   "title": "Verbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data = from(bucket: \"nodered-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"770C\")\r\n  |> filter(fn: (r) => r._field == \"Consumption\")\r\n\r\nfirstVal = data |> first()\r\nlastVal  = data |> last()\r\n\r\nunion(tables: [firstVal, lastVal])\r\n  |> group()  // merge all rows into one table\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value\r\n      })\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _value: if r.last - r.first >= 0 then r.last - r.first else -(r.last - r.first),\r\n      _field: \"delta_Consumption\"\r\n  }))\r\n"
    }
   ]
  }
 ]
}